### ISSUE TITLE
Z-Fighting in the Cube

### ISSUE THREAD

**Issue by richardpaulraj** [pachoclo/vite-threejs-ts-template#89]
Downside of the cube is facing z-fighting

**Comment by JackEdwardLyons** [comment]
Just throwing out some options to mitigate z-fighting, you could try:

- Increase Depth Buffer Precision: Use a higher precision depth buffer if possible.

- Adjust Near and Far Planes: Ensure that the near and far clipping planes of the camera are as tight as possible around the scene to maximise depth buffer precision.

```
// Adjust the plane position slightly along the Y-axis
plane.position.y = -0.01;
```

- Offset Geometry: Slightly offset one of the surfaces to avoid them having the same depth value.

- Use Polygon Offset: Apply a small offset to the rendering of polygons to separate overlapping surfaces.

```
const planeMaterial = new MeshLambertMaterial({
  color: 'gray',
  emissive: 'teal',
  emissiveIntensity: 0.2,
  side: 2,
  transparent: true,
  opacity: 0.4,
  polygonOffset: true,  // Enable polygon offset
  polygonOffsetFactor: 1,  // Positive value to push the plane back
  polygonOffsetUnits: 1,  // Units to offset
});
```

- Adjusting camera settings or using material properties to apply a polygon offset.

```
camera = new PerspectiveCamera(50, canvas.clientWidth / canvas.clientHeight, 0.1, 50);
```
